import React from 'react'
import Head from 'next/head'

function About(props)
{
    return(
        <>
         <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main>
            <h1>Hello about</h1>
        </main>
        </>
    )
}

export default About;