import Head from "next/head";
import React from "react";

function Blogs() {
    return(
        <>
            <Head>
                <title>Blogs</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className = "w-screen h-screen flex justify-center">
                <div className="mt-36">
                    <div className="text-center text-slate-100 font-bold text-4xl">
                        <h1>Hey this page is still in Development!</h1>
                    </div>
                </div>
            </main>
        </>
    )
}
export default Blogs;