import React from 'react'
import Head from "next/head";
import ContactInfo from "../components/ContactInfo";
import ContactInputs from "../components/ContactInputs";

function Contact() {
    return (
        <>
            <Head>
                <title>Contact</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="w-full h-full md:w-screen md:h-screen flex justify-center bg-[#0B1223] pb-16">
                <div className="sm:mt-36 mt-20 w-full sm:w-[90%] md:w-[80%] lg:w-[70%] max-w-6xl">
                    <div className="text-center text-slate-100 font-bold text-4xl mb-12">
                        <h1>CONTACT</h1>
                    </div>
                    <div className="flex flex-col sm:flex-row items-center justify-center w-full gap-8 sm:gap-12">
                        <div className="w-full sm:w-1/2">
                            <ContactInfo/>
                        </div>
                        <div className="w-full sm:w-1/2 bg-[#0B1223]">
                            <ContactInputs/>
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}

export default Contact;