import React from 'react'
import Head from "next/head";
import ContactInfo from "../components/ContactInfo";
import ContactInputs from "../components/ContactInputs";

function Contact() {
    return (
        <>
            <Head>
                <title>Contact</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className="w-full h-full md:w-screen md:h-screen flex items-center justify-center md:flex-row">
                <div className = "">
                    <div className="text-center text-slate-100 font-bold text-4xl">
                        <h1>Contact US</h1>
                    </div>
                    <div className="block justify-center  mt-16 space-x-0 md:space-x-8 space-y-40 md:space-y-0">
                        <div className="h-96">
                            <ContactInfo/>
                        </div>
                        <div className="w-[40%] bg-slate-6 h-max mt-8 md:mt-0">
                            <ContactInputs/>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default Contact;