import Head from 'next/head'
import styles from './index.module.css';
import Card from '../components/Card.tsx';
import ProfileBox from '../components/ProfileBox';
import Bar from "../components/Bar";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.backgrounddiv}>
                <div className = "flex w-screen">
                    <div className="">
                        <Bar/>
                    </div>
                    <div className="h-screen grow flex justify-center items-center ml-auto">
                        <ProfileBox/>
                    </div>
                </div>
            </main>
        </>
    )
}
