import React from 'react'
import Head from 'next/head'
import styles from './index.module.css';
import Card from '../components/Card.tsx';
import ProfileBox from '../components/ProfileBox';
import Bar from "../components/Bar";
import Navigation from '../components/Navigation'

export default function Home(props) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="w-full bg-[#0B1223]">
                    <div className="h-screen grow flex justify-center items-center ml-auto">
                            <ProfileBox/>
                    </div>
            </main>
        </>
    )
}
