import React from 'react'
import Head from "next/head";
import ResumeBox from "../components/ResumeBox";

function Resume() {
    return (
        <>
            <Head>
                <title>Resume</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="w-screen h-screen flex justify-center">
                <div className="mt-36">
                    <div className="text-center text-slate-100 font-bold text-4xl">
                        <h1>MY SKILLS</h1>
                    </div>
                    <div className = "flex w-auto min-h-full">
                        <ResumeBox ration={0.3}/>
                        <ResumeBox ration={0.5}/>
                        <ResumeBox ration={4}/>
                        <ResumeBox ration={0.7}/>
                    </div>
                </div>
            </main>
        </>
    )
}

export default Resume;