import React from 'react'
import Head from "next/head";
import ResumeBox from "../components/ResumeBox";
import SkillBox from "../components/SkillBox";

function Resume() {
    return (
        <>
            <Head>
                <title>Resume</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="w-screen h-screen flex justify-center">
                <div className="mt-36">
                    <div className="text-center text-slate-100 font-bold text-4xl">
                        <h1>MY SKILLS</h1>
                    </div>
                    <div className = "flex w-auto ">
                        <ResumeBox ration={90} percentText={85} title="UI/UX DESIGN"/>
                        <ResumeBox ration={150} percentText={80} title="Backend Development"/>
                        <ResumeBox ration={360} percentText={95} title="FrontEnd Development"/>
                        <ResumeBox ration={150} percentText={75} title="MobileApp Development"/>
                    </div>
                    <div className="flex flex-wrap">
                        <SkillBox skillTitle={"JavaScript"} skillPercent={80}/>
                        <SkillBox skillTitle={"TypeScript"} skillPercent={90}/>
                        <SkillBox skillTitle={"React"} skillPercent={60}/>
                        <SkillBox skillTitle={"C++"} skillPercent={40}/>
                        <SkillBox skillTitle={"C#"} skillPercent={65}/>
                        <SkillBox skillTitle={"Java"} skillPercent={30}/>
                    </div>
                </div>
            </main>
        </>
    )
}

export default Resume;