import Head from "next/head";
import React from "react";
import {useDispatch, useSelector} from "react-redux";
import {fetchGithubRepos} from "../slices/apiSlice";
import {RootState} from "../store";
import WorksNavigationButtons from "../components/WorksNavigationButtons";
import ProjectBox from "../components/ProjectBox";
import {func} from "prop-types";

function Works()
{
    const FetchedRepos = useSelector((state: RootState) => state.gitApi.filteredRepos);
    const dispatch = useDispatch();
    const [loadCount,setLoadCount] = React.useState<number>(6);

    React.useEffect(() => {
            // @ts-ignore
            dispatch(fetchGithubRepos());
    },[])

    function handleLoadMore() {
        setLoadCount(loadCount + 6);
    }

    if(FetchedRepos == null)
    {
        return(
            <div>Loading...</div>
        )
    }
    return(
        <>
            <Head>
                <title>Works</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className = "w-full flex justify-center p-12">
                <div className="mt-36 w-full">
                    <div className="text-center text-slate-100 font-bold text-4xl">
                        <h1>Works</h1>
                    </div>
                    <div className = "block">
                        <div className="flex justify-center">
                            <WorksNavigationButtons/>
                        </div>
                        <div className="w-full h-full flex space-x-3 justify-center flex-wrap">
                            {
                                FetchedRepos?.slice(0,loadCount).map((work,key) => (
                                        <ProjectBox key = {key} {...work}/>
                                ))
                            }
                        </div>
                        <div className = "flex justify-center">
                            <button
                                className="bg-blue-500 mt-6 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
                                onClick = {handleLoadMore}
                            >
                                Load More...
                            </button>
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}
export default Works;